#!/usr/bin/env bash
#Installs and configures HAproxy on your server

sudo apt-get update
sudo apt-get -y instal haproxy

#configure haproxy configuration to distribute requests using roundrobin algorithm
echo "
frontend cynthiatonui.tech
        bind *:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 187699-web-01 54.209.214.130:80 check
        server 187699-web-02 52.23.245.22:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" |sudo tee -a /etc/default/haproxy
sudo service haproxy restart
