#!/usr/bin/env bash
# Script that generates a MYSQL dump and creates a compressed archive out of it.

mysqldump -u root -p "$1" --all-databases > backup.sql
tar -cvfz "$(date +%d-%m-%Y)".tar.gz backup.sql
