#!/usr/bin/env bash
#A bash script that displays a list of currently running processes
#Shows all processes, for all users, including those without TTY
#Display in a user-oriented format
#Show process hierachy

ps -auxf
