#!/usr/bin/env bash
# A bash script that displays To infinity and beyond
# With sleep 2 in between ech iteration
# I am invincible!!! when receiving a SIGTERM signal

while true
do
echo "To infinity and beyond"
sleep 2
trap 'echo "I am invincible!!!"' SIGTERM
done
