#!/usr/bin/env bash
#Bash script that displays the time for 12hours and 59minutes

hour=0
minute=1

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute++))
	done
	(( hour++ ))
done
